### PR TITLE
Add files to develop / build with VS Code

### PR DESCRIPTION
**Pull request by HorstBaerbel**

### CODE REVIEW

**Comment by HorstBaerbel** [comment]
Updated the pull request with new changes

**Comment by TricksterGuy** [comment]
Alright not a VSCode user here.  Alright seems to read from cmake as long as this doesn't cause me any extra work / disrupt my workflow I'm fine with it.

Thanks for those fixes.

**Comment by HorstBaerbel** [comment]
Yes. It uses CMake. Did you take a look at the second commit? I added -help / --help which seems to be pretty much standard.

**Comment by TricksterGuy** [comment]
Yup I did thanks for that again.

**Pull request merged**
