### PR TITLE
Finding ImageMagick using pkgconfig instead of find_package

### PR DESCRIPTION
**Pull request by cgokmen**
The commit involves making CMake find ImageMagick using pkgconfig instead of find_package due to the latter not functioning properly on OSX, should not have any adverse effects on any platform.

With this fix the project finally compiles as expected on OSX and therefore I will be able to make a Homebrew formula available once (if) you merge it.

### CODE REVIEW

**Comment by cgokmen** [comment]
Update: I put up a Homebrew formula on my tap linked to the current version on my fork for testing: https://github.com/skyman/homebrew-gt/blob/master/Formula/nin10kit.rb

To install,
```
brew install skyman/gt/nin10kit
```

Both nin10kit and nin10kitgui confirmed working on my 2016 MBP 15" Touch Bar as well as a friend's 2012 MBP 15" Retina.

**Comment by TricksterGuy** [comment]
Wrap it in an OS check because I am paranoid and I'll merge.

**Comment by TricksterGuy** [comment]
Now with my latest commit I have to ask...

What was the problem with compiling on OSX?

**Comment by cgokmen** [comment]
On OSX, cmake fails at the find_package line for ImageMagick saying the components could not be found, and I could not trace the issue to its root. pkg_config just works though, so ended up choosing to use that instead. The error is attached if you're interested.

screen shot 2017-03-26 at 9 44 53 pm

I am closing this pull request, will make the change OS-dependent as you said.

Also, question: the CMake file includes pkgconfig but doesn't use it anywhere apart from the small change I made, is that intended? It was very useful anyway...

**Pull request closed without merging**
